version: '3'
services:
  mysql_dev:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=tcc
      - MYSQL_DATABASE=tcc
      - MYSQL_USER=tcc
      - MYSQL_PASSWORD=tcc
    expose:
      - '3306'
    ports:
      - '3306:3306'
